### ISSUE TITLE
BungeeCord Online Placeholder Doubling

### ISSUE THREAD

**Issue by Elijeh** [Puharesource/TitleManager#112] opened 2017-02-11 11:02 UTC
When I use the BungeeCord online placeholder (%{BUNGEECORD-ONLINE}) then sometimes the player count will double (e.g 1 to 2 players, 2 to 4 players, etc).

**Comment by LemonLight** [comment] 2017-02-18 14:15
Yep it appears when players are switching/disconnect to an other server.

**Comment by Puharesource** [comment] 2017-03-05 23:21
@Elijeh @LemonLight 

While I've heard of others having this issue, I'm simply unable to replicate this. (Might be because I'm testing it with 2 accounts and 2 servers). Is there a more specific way to replicate this issue?

**Comment by Elijeh** [comment] 2017-03-06 06:36
Would it help if I provided you a server so that you can see this replicated?

**Comment by Elijeh** [comment] 2017-03-06 06:50
I'm not sure how this could be replicated, all I know is that I'm having this issue and it's annoying.

If you'd like, I can provide you with my server so you can see that the issue exists (it will occasionally double the player count).

**Comment by LemonLight** [comment] 2017-03-06 18:42
Setup 1 Bungeecord and 2 spigot servers and ask a friend to connect to your servers with you to see the problem. (I think it needs 2 different IP address to replicate the problem). Stay on one server and ask to your friend connect across the servers, normally you will see the counters doubled.

@Elijeh Have you got Hub Magic installed on your Bungeecord ? Maybe it is the common thread. Because hub magic plugin can sometimes have weird comportment.

**Comment by Elijeh** [comment] 2017-03-06 18:51
@LemonLight
For me my server doesn't need another player to be on the server. It could be one, two etc players on the server and it'll still double the total count.

And yes I have Hub Magic installed on my BungeeCord.

**Comment by Puharesource** [comment] 2017-03-06 19:13
@LemonLight @LemonLight 
Could you test this without Hub Magic, possibly? As I'm whenever my alt account jumps from server to server, it works as intended.

If the error still occurs, could you please join my Discord support chat and I'll upload a dev build for you to try (as that's the one I'm testing with).

**Comment by Elijeh** [comment] 2017-03-06 19:14
Alright, I'll try without Hub Magic

**Comment by Elijeh** [comment] 2017-03-06 19:28
@Puharesource 

Just tested without Hub Magic and my player count still doubles

**Comment by LemonLight** [comment] 2017-03-06 20:01
@Elijeh Same issue too, when I am alone, it doubles :/

**Comment by chrisbruijnes** [comment] 2017-04-20 12:08
I also got this issue @Puharesource

**Comment by chrisbruijnes** [comment] 2017-04-22 19:31
Anyone who already found a fix to this?

**Comment by LemonLight** [comment] 2017-04-23 20:47
No, the problem still persists on my network

**Comment by chrisbruijnes** [comment] 2017-04-26 13:12
@Puharesource

**Comment by christiaanbruijnes** [comment] 2017-05-04 12:45
I don't think this will be fixed shortly, which is weird since it stops a lot of people updating the plugin.

**Comment by flash8ack** [comment] 2017-05-04 21:22
please fix it

**Comment by LemonLight** [comment] 2017-05-05 20:29
@flash8ack please wait for it. This is not an important bug, it's only "aesthetic" 

@Puharesource If you want to see the bug in action, you can contact me or try to connect to mc.advencraft.fr (it's a french server) press tab and try to navigate between the different servers, you should see the bug appear

**Comment by DKing328** [comment] 2017-05-11 06:00
Hi there, I made a post on the discussions page on Spigot about this exact issue earlier today, and happened to stumble across this report. My lobby server is the only out of six servers on my network experiencing this exact issue. Hopefully a fix will be out soon.

**Comment by christiaanbruijnes** [comment] 2017-05-11 07:55
We have been waiting for over 3 weeks now, with no answer at all.

**Comment by Puharesource** [comment] 2017-05-16 20:21
I'm aware and I'm very sorry, I've seen this happening on other servers, though I've been completely unable to reproduce it locally. Hence one of the reasons why I haven't been able to fix it. The other reason (and I know it might sound like a bad excuse) is that I simply haven't had time to fix the issues that TitleManager has lately, as I've been swamped with work.

However, I do promise that once I either get time or this issue becomes and issue with my work as well, it'll be fixed, but for now I'm just not able to.

**Comment by christiaanbruijnes** [comment] 2017-05-17 09:41
That is understandable, let us know once you have time.

**Comment by christiaanbruijnes** [comment] 2017-06-11 19:32
@Puharesource Already fixed this?

**Comment by Puharesource** [comment] 2017-06-13 22:52
@christiaanbruijnes 
I recently updated the plugin to support 1.12 this also pushed a few patches I had made over the time of not releasing anything, this could have fixed it, but I highly doubt it. Try the build out and report back if it's fixed. :)

**Comment by AngellitoX** [comment] 2017-06-18 20:20
@Puharesource I can confirm the issue is still appearing. It's happening on my Lobby too.

Information:
-TitleManager 2.0.7
- Spigot latest build (cd6ba679886)
- Latest Bungeecord build

**Comment by Puharesource** [comment] 2017-06-18 20:49
Alright, thanks for the update

**Comment by StefanTod** [comment] 2017-07-10 21:01
It is appearing because of PlaceholderAPI. As soon as I add the plugin it starts getting doubled. I think it is because both plugins have the same placeholder for the same thing.

**Comment by DKing328** [comment] 2017-07-10 21:38
Ah, odd. I run 8 servers using TitleManager and PlaceholderAPI both, and yet only 2/8 servers experience this issue. One of them experience it only on occasion, while the other is constantly doubled. Is there something in particular that triggers it to happen?

**Comment by StefanTod** [comment] 2017-07-11 07:30
I only had the doubling in my survival server where I had both the plugins. On the moment I added the PlaceholderAPI on my hub to mess with some holograms, it immediately started. I added it to one more server just to be sure it's from that , and it started happening again. I don't know what else could trigger it.

**Comment by DKing328** [comment] 2017-07-12 01:12
I just tested this theory on my server which is experiencing this issue the most severe (my hub/lobby server). I completely removed PlaceholderAPI from the plugins folder and restarted, however, the issue was still persisting. Maybe PlaceholderAPI has something to do with it, but it must not be the main cause, since it was still occuring after it was removed.

**Comment by Dimatert9** [comment] 2017-07-27 17:38
This causing when other plugin get online with SubChannel "GetOnline" and server name "ALL".

**Comment by Dimatert9** [comment] 2017-07-27 17:41
https://github.com/Puharesource/TitleManager/blob/master/src/main/kotlin/io/puharesource/mc/titlemanager/bungeecord/BungeeCordManager.kt#L61

if (server.equals("ALL")) return;


https://www.spigotmc.org/wiki/bukkit-bungee-plugin-messaging-channel/#playercount

**Comment by Puharesource** [comment] 2017-07-27 20:19
I'll release a build that fixes this asap

**Comment by Puharesource** [comment] 2017-07-27 20:19
Thank you @Dimatert9

**Closed** 2017-07-27 20:26 UTC
Labels: Bug
