### ISSUE TITLE
TitleManager Blocking Joins to the Server

### ISSUE THREAD

**Issue by Fluxty** [Puharesource/TitleManager#142] opened 2017-06-23 22:12 UTC
TitleManager is causing issues with players joining our 1.8.8 server. Every once in a while nobody will be able to join, running a title broadcast command fixes the issue, the console is spammed with UUID's that were trying to join but could not. Scoreboard is disabled.

TitleManager version: TitleManager v2.0.7 (This was also happening on previous versions but not  1.x)
TM config:  https://hasteb.in/tatuxesele.coffee

We use the TMAPI to broadcast actionbars when a booster is active. We have around 170+ players on this particular server instance. This is what it looks like in console when people are trying to join but cannot: https://hasteb.in/kovozenidu.avrasm

And this is what happens when the issue is resolved by running /tm bc <message>

https://hasteb.in/dunehigude.css

This is a critical issue for us

**Comment by Fluxty** [comment] 2017-06-25 22:43
Update: We reverted back to 1.5.13, the issue DOES still occur on this version but it is very very rare and much more manageable.

**Comment by Puharesource** [comment] 2017-07-30 18:58
This is a duplicate of #139 please go there as there's a possible fix for this issue in that discussion.

**Closed by Puharesource** 2017-07-30 18:58 UTC
Labels: Bug
